### ISSUE TITLE
Warning: Error in [[: attempt to select less than one element in get1index   1: runApp

### ISSUE THREAD

**Issue by lananh-ngn** [tbaccata/amica#15]
Hello,
Thank you for developing this tool. I am using FragPipe output. I used to be able to use it but now I am stuck on a faded grey page after clicking on Analyze both on the web version and the R version. On the R version, in the terminal, this error is displayed `Warning: Error in [[: attempt to select less than one element in get1index
  1: runApp`
Could you help please ? 
Thank you in advance for your help. 

Input file [firsttwolines.txt](https://github.com/tbaccata/amica/files/9503052/firsttwolines.txt)
Contrast file [contrast.txt](https://github.com/tbaccata/amica/files/9503048/contrast.txt)
Design file [design.txt](https://github.com/tbaccata/amica/files/9503051/design.txt)

**Comment by tbaccata** [comment]
Hello!


Thanks for sending example files, I could reproduce the error. 

The issue are the sample names, they start with a number and contain special characters ("-" the hyphen).
R's read command(s) checks the column names whether they are in a correct format, 
and finally coerces column names to syntactically valid names. 

There should have been some error messages, and definitely some checks in the software. 
I will have a deeper look into this, this should be reported back to the user.

Does it work when you use this exp. design? ( here I've appended an X in front of all samples, and removed special characters "-" with a dot ".")
[expDesign.txt](https://github.com/tbaccata/amica/files/9504020/expDesign.txt)


Best,
Sebastian

**Comment by lananh-ngn** [comment]
Sebastian,
Thank you for the quick answer. I tried to run the tool with file you provided in your message and with the names changed in the fragpipe input file. However, I still have the same error.
Thank you in advance,
Lan Anh

**Comment by tbaccata** [comment]
I will have a look at this, I hope I can solve this until tomorrow.
I'll get back to you.

This error only affects FragPipe input.

**Comment by lananh-ngn** [comment]
Thank you for your quick feedback. Also, I had to change the headers so that it fits amica's requirements but I think FragPipe  changed the output in their recent upgrade: https://github.com/Nesvilab/FragPipe/issues/774.
Best regards,
Lan Anh

**Comment by tbaccata** [comment]
Hello  Lan Anh,

please try again, it should work now on the server, and the same code is also already on github.
You can use your original exp. design, amica automatically handles special characters now.

You did get an error message, that `Total Intensity` and `Unique Intensity` columns were missing, that's why you renamed them, is this correct? 
The underlying issue in amica's code was, that some `LFQ intensity` columns were expected (either suffixed per sample with `Intensity`, `RazorIntensity`, or `MaxLFQ Intensity` in the combined_proteins.tsv file) in the analysis - that's what caused the error.  

Relevant columns from FragPipe's output didn't change in their update, only a couple of Intensity columns have been removed. That's why amica complained about missing intensity columns. 
Otherwise the same columns are present, that are parsed by amica.

I've fixed this behavior, FragPipe v18 output is now automatically handled by amica.
So you don't need to rename the columns your original file (although it should also work with the input file you've uploaded here).

Please let me know, whether everything works for you.


Best,
Sebastian

**Comment by lananh-ngn** [comment]
Sebastian,
Thank you for the quick solve. I tried it with the source code and it works fine. Thank you also for the clear explanation!
Best regards,
Lan Anh
