### ISSUE TITLE
Enrichment analysis and gene names

### ISSUE THREAD

**Issue by cutleraging** [tbaccata/amica#17]
Hello and great work on this tool! Hope that you are able to get this published very soon :)

I would like to request a new feature for the enrichment analysis. Could you please have the genes from the input that are associated with each enrichment term be output in a column in the output table? This would be great to know which genes are the reason for a certain enrichment.

Thanks!

**Comment by tbaccata** [comment]
Hello!

Thanks! 
When you click on the "Show genes in functional enrichment?" tick box in the functional enrichment section,
you get an additional column called "intersection" in the funct. enrichment table.

You can use an advanced query in the output table to only select proteins annotated with a specific term, described here:
https://github.com/tbaccata/amica/wiki/02-Differential-Abundance#advanced-queries

Due to technical reasons, it is quite difficult to include a new column in the output tab. 
Using the advanced query should hopefully help.

Cheers,
Sebastian
